version: '3.1'
services :
  db:
    image: postgres:14-alpine
    ports:
      - "${PG_PORT}:5432"
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - ${ADM_PORT}:8080
