version: '3.1'
services :
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: recipes
      POSTGRES_PASSWORD: recipes
      POSTGRES_DB: recipes 
  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080
