# Generated by Django 3.2.8 on 2021-11-06 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipeIngredient',
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unity',
            field=models.CharField(choices=[('g', 'gramme'), ('mg', 'milligramme'), ('l', 'litre'), ('ml', 'millilitre'), ('kg', 'kilogramme'), ('nb', 'nombre'), ('cc', 'cuillère à café'), ('v', 'verre (petit)')], max_length=10),
        ),
        migrations.CreateModel(
            name='IngredientList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unity', models.CharField(choices=[('g', 'gramme'), ('mg', 'milligramme'), ('l', 'litre'), ('ml', 'millilitre'), ('kg', 'kilogramme'), ('nb', 'nombre'), ('cc', 'cuillère à café'), ('v', 'verre (petit)')], max_length=10)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe')),
            ],
        ),
    ]
