# Generated by Django 3.2.8 on 2021-10-31 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        CITextExtension()
    ]
